### ISSUE TITLE
bug on swapping 0xd to any coins

### ISSUE THREAD

**Issue by zillabytes** [solidlyexchange/solidly#53]
transaction history : https://ftmscan.com/tx/0x163fed7c4efd2ea2a47cfc563c61e23a67766bc172125987e2d3d06f91b6c4c0

when I swap 0xd to sex only half of the value is being received because its route on FTM not on USDC maybe you change it to route 0xd>usdc> to any coins

please change it.

**Comment by NiQlaus** [comment]
I have lost all my fund in a Solidly transaction. 
When the transaction executed, it returned 0.01% of what I should have received:
https://ftmscan.com/tx/0x106b553efb510863f155290ff9e61801244367f1493aa219efaefb46490c0e82

It seems the exchange chose a fixed LP without liquidity when there was another variable LP with all the liquidity (see picture attached). It means there is no verification of the LP liquidity when automatically selecting fixed or variable LPs. 

Besides, the routing seems not to be correct. One guess is that it is quoting the price from the correct route but using the wrong one for the swap. The UI is not selecting the correct route for the swap. Picture attached shows how the value quoted is correct, but once transaction is executed, a different amount is received.

The UI/frontend is not public and not open for audits. Note the smart contracts have a bug bounty program:
https://immunefi.com/bounty/solidly/
Yet, the UI itself can be more damaging for Solidly and cannot be reviewed. My funds are now lost and I cannot even claim for some compensation when reporting the bug...
![Solidly bug 1](https://user-images.githubusercontent.com/83178929/155804918-840dfcbe-489b-46b3-ab36-0ed7854d2dd4.JPG)
![Solidly bug 2](https://user-images.githubusercontent.com/83178929/155804920-89d6735d-c41d-4f39-94e9-a79c286fd1ce.JPG)
![Solidly bug 3](https://user-images.githubusercontent.com/83178929/155804921-34f88ef4-434b-4999-a3e8-dd4fb5976ff4.JPG)
![Solidly bug 4](https://user-images.githubusercontent.com/83178929/155804922-e206b894-d58a-4c6d-9f10-259dfcfcbad0.JPG)

**Comment by zillabytes** [comment]
Can I ask if I can get ftm refund for this error or not? tnx!
