### ISSUE TITLE
Swap Issues 0xDAO Tokens to Solid

### ISSUE THREAD

**Issue by desolacarlo** [solidlyexchange/solidly#58]
Hello! 
I tried the swap for OXD - SOLID (3k OXD results to 9.51 SOLID) I made a mistake because supposedly I want to build vAMM OXD USDC LP so I swapped back right away FROM SOLID (9.51) TO OXD which gives back only 2k OXD
I lost my assets ang hopefully I can get it back
You can review the transaction hash in here 0x6Cc42B4D7712498B45eE351CF76083896f6a3ad5

**Comment by jbright2** [comment]
You got rekt by slippage, must have routed through a pool with no liquidity.

Unfortunately, this isn't a CEX where somebody can just reimburse you. Transactions done through the chain cannot be reversed... Unless you fork fantom. kek, reminds me of eth/etc split

**Comment by desolacarlo** [comment]
But I set my slippage low

**Comment by zillabytes** [comment]
got the same problem bro..  swap my oxd to sex only half been received its route to FTM which low LP it should be route on USDC
