### ISSUE TITLE
I don't see all assets (and therefore cannot add liquidity)

### ISSUE THREAD

**Issue by andreaamici** [solidlyexchange/solidly#59]
Good morning, since yesterday I run into this bug/problem. when I am in the swap section or when I am about to add liquidity I do not see all the assets I own in the portfolio. This does not allow me to add liquidity or make trades in the exchanges.
Yesterday I solved the problem momentarily by swapping the only asset that I could see (FTM) with the asset that I want to show. After the swap (1 FTM) I correctly load all the tokens of that asset.
example: yesterday i had to add liquidity in the beets/fbeets pool i had (about) 500 beets and 450 fbeets, it did not show them to me in the portfolio (and therefore i could not add liquidity), then i exchanged 1 ftm for beets, after the exchange all the beets are in the pool, same thing for fbeet

I attach two photos, in the first the assets that solidly sees, in the second all the assets that I have and that spookyswap shows me correctly

![proof1](https://user-images.githubusercontent.com/100516652/155880796-0dcff53f-905a-472e-b799-27751dbe04eb.PNG)
![proof2](https://user-images.githubusercontent.com/100516652/155880798-a5569b49-7601-4459-b397-0a379d82402b.PNG)

**Comment by gnalsa** [comment]
This repo is for the contracts, you should move issue to front-end project https://github.com/solidlyexchange/solidly.exchange

Also, you might want to clarify if the asset name can be manually entered?

**Comment by andreaamici** [comment]
Today everything seems to be working properly. 
However, yes I could enter the asset manually but still the balance was 0 when in reality I held more than zero, and this prevented me from proceeding both in the buy/sell phase and in the add liquidity phase.
Now I don't know if it was my loading error or something else, but now from both computers and with different networks it seems to work perfectly.
thanks
