### ISSUE TITLE
Limit SOLID harvest frequency to prevent auto-compounding bots from making gas price permanently very high

### ISSUE THREAD

**Issue by Pi-Rr** [solidlyexchange/solidly#60]
Gas price on Fantom has been out of control since Solidly launched, continuously averaging ~2000 Gwei vs. ~300-400 Gwei pre launch.
The No. 1 and No. 5 largest gas consumers (at time of writing) are SOLID farming bots:
* https://ftmscan.com/address/0x3d87a22c6094b623636554a68b03d1f71c869dc7#tokentxns
* https://ftmscan.com/address/0x26e1a0d851cf28e697870e1b7f053b605c8b060f#tokentxns

I know the Solidly code is immutable, but I believe most Solidly users and participants in the Fantom ecosystem would be happy to go through a one-off migration if it could bring back gas price to more reasonable levels across the entire Fantom ecosystem.
A Solidly v2 release would also give the opportunity to fix any other identified issues since launch, including any security concerns that might be identified during the ongoing audits.

I don't have a perfect solution to propose, but I think this is an important dialogue to have.
A way to limit those abuse could be to divided harvest into "epoch" of let's say [6 hours] and allows to call the ClaimRewards fonction only once every epoch.
This is just an idea, I am not a developer and I am sure there are plenty of big brains that will be able to come up with a better solutions.

Hope the team will consider this, and thanks for the amazing work!

**Comment by AbiHanna** [comment]
True that's a good proposal

**Comment by uponatime2019** [comment]
Fantom network really have gwei problem since solidly launchec, last night gwei go 4000 for mid speed, when Solid price go up, if team accept author idea, may be allow rewards can claim random time base on address format?
